
import { Devotional, DayPlan } from "../types";

/**
 * Base de dados oficial com as 365 reflexões fornecidas pelo usuário.
 */
const rawData: Record<number, [string, string]> = {
  1: ["Salmos 23:1 - \"O Senhor é o meu pastor; nada me faltará.\"", "Comece o ano/ciclo lembrando que o suprimento vem de quem guia, não do caminho em si. Se Ele é o Pastor, você tem tudo."],
  2: ["Mateus 6:34 - \"Não vos inquieteis, pois, pelo dia de amanhã...\"", "A ansiedade tenta roubar a paz do hoje com problemas que talvez nem existam amanhã. Foque na graça disponível para o agora."],
  3: ["Filipenses 4:13 - \"Tudo posso naquele que me fortalece.\"", "Esta não é uma promessa de superpoderes, mas de resistência: você pode enfrentar qualquer circunstância através de Cristo."],
  4: ["Provérbios 3:5 - \"Confia no Senhor de todo o teu coração...\"", "Confiar exige soltar o controle. Não tente entender tudo; apenas descanse na sabedoria de Quem vê o fim desde o princípio."],
  5: ["Isaías 41:10 - \"Não temas, porque eu sou contigo...\"", "O medo perde a força quando reconhecemos a presença. Você não está sozinho nas batalhas desta semana."],
  6: ["Lamentações 3:22-23 - \"As misericórdias do Senhor se renovam a cada manhã.\"", "Ontem passou. Se houve erros, a graça de Deus oferece uma folha em branco hoje. Recomece sem culpa."],
  7: ["João 14:27 - \"Deixo-vos a paz, a minha paz vos dou.\"", "A paz do mundo depende de circunstâncias; a paz de Jesus depende da natureza d'Ele. Mantenha o coração calmo mesmo no caos."],
  8: ["Salmos 46:10 - \"Aquietai-vos e sabei que eu sou Deus.\"", "Às vezes, a maior demonstração de fé não é agir, mas parar e reconhecer que o controle pertence a Ele."],
  9: ["Josué 1:9 - \"Sê forte e corajoso... o Senhor é contigo.\"", "A coragem não é ausência de medo, mas a obediência apesar do medo, confiando na companhia divina."],
  10: ["1 Pedro 5:7 - \"Lançando sobre ele toda a vossa ansiedade.\"", "Deus se importa com os detalhes. Não carregue fardos que Ele já se ofereceu para levar por você."],
  11: ["Romanos 8:28 - \"Todas as coisas cooperam para o bem...\"", "Até os imprevistos e as dores são usados por Deus para tecer um propósito maior na sua vida."],
  12: ["Mateus 5:14 - \"Vós sois a luz do mundo.\"", "A luz não faz barulho, ela apenas brilha. Que suas ações hoje revelem a bondade de Deus sem precisar de palavras."],
  13: ["Salmos 119:105 - \"Lâmpada para os meus pés é a tua palavra.\"", "A Bíblia pode não mostrar o caminho inteiro de uma vez, mas dá luz suficiente para o próximo passo."],
  14: ["Gálatas 6:9 - \"E não nos cansemos de fazer o bem...\"", "A colheita é certa, mas exige paciência. Não desista do que é certo só porque o resultado ainda não apareceu."],
  15: ["Hebreus 11:1 - \"A fé é a certeza das coisas que se esperam.\"", "Fé é crer no que não se vê para que se possa suportar o que se vê."],
  16: ["Salmos 37:4 - \"Deleita-te no Senhor, e ele te concederá os desejos.\"", "Quando você encontra prazer em Deus, seus desejos começam a se alinhar com a vontade perfeita d'Ele."],
  17: ["Efésios 4:32 - \"Sede uns para com os outros benignos...\"", "O perdão que oferecemos aos outros é o reflexo do perdão que já recebemos de Cristo."],
  18: ["Tiago 1:5 - \"Se algum de vós tem falta de sabedoria, peça-a a Deus.\"", "Inteligência é saber o que dizer; sabedoria é saber se deve ou não dizer. Peça o guia do alto hoje."],
  19: ["2 Coríntios 12:9 - \"O meu poder se aperfeiçoa na fraqueza.\"", "Sua limitação não é um impedimento para Deus, mas o cenário onde a força d'Ele mais aparece."],
  20: ["Mateus 11:28 - \"Vinde a mim, todos os que estais cansados.\"", "O descanso real não vem de férias, mas de uma pessoa: Jesus. Entregue o cansaço da alma a Ele."],
  21: ["Colossenses 3:23 - \"Tudo o que fizerdes, fazei-o de todo o coração.\"", "Não trabalhe apenas para homens. Transforme sua rotina comum em um ato de adoração a Deus."],
  22: ["Salmos 121:1 - \"Elevo os olhos para os montes: de onde me virá o socorro?\"", "O socorro não vem dos montes, mas do Criador deles. Olhe para cima, não para os problemas ao redor."],
  23: ["João 8:32 - \"E conhecereis a verdade, e a verdade vos libertará.\"", "A verdade bíblica nos liberta das mentiras que o mundo e nossos próprios sentimentos nos contam."],
  24: ["Salmos 34:8 - \"Provai e vede que o Senhor é bom.\"", "A bondade de Deus não é uma theory para ser estudada, mas uma experiência para ser vivida diariamente."],
  25: ["1 Tessalonicenses 5:18 - \"Em tudo dai graças.\"", "Gratidão não é uma resposta a coisas boas, é uma postura diante de qualquer circunstância."],
  26: ["Isaías 40:31 - \"Mas os que esperam no Senhor renovarão as forças.\"", "Esperar em Deus não é tempo perdido, é tempo de preparação e renovo."],
  27: ["Provérbios 4:23 - \"Guarda o teu coração, porque dele procedem as fontes da vida.\"", "O que você permite entrar na sua mente e coração define a direção da sua história."],
  28: ["Jeremias 29:11 - \"Eu é que sei que pensamentos tenho a vosso respeito.\"", "O futuro pode ser incerto para você, mas ele já foi planejado com paz e esperança por Deus."],
  29: ["Mateus 6:33 - \"Buscai primeiro o Reino de Deus...\"", "Quando as prioridades estão no lugar certo, as outras necessidades da vida encontram seu equilíbrio."],
  30: ["Salmos 103:2 - \"Bendize, ó minha alma, ao Senhor, e não te esqueças...\"", "Combata o desânimo fazendo uma lista de todos os benefícios que Deus já te concedeu até aqui."],
  31: ["Filipenses 4:6 - \"Não andeis ansiosos por coisa alguma.\"", "Substitua a preocupação pela oração. Falar com Deus transfere o peso da sua mente para as mãos d'Ele."],
  32: ["Salmos 1:1 - \"Bem-aventurado o homem que não anda segundo o conselho dos ímpios.\"", "Suas amizades e as vozes que você ouve determinam o quão frutífera será a sua jornada."],
  33: ["1 João 4:18 - \"No amor não há medo; pelo contrário, o perfeito amor expulsa o medo.\"", "Quanto mais você compreende o quanto é amado por Deus, menos poder o medo tem sobre você."],
  34: ["Salmos 51:10 - \"Cria em mim, ó Deus, um coração puro.\"", "A verdadeira mudança começa de dentro para fora. Peça a Deus para alinhar suas intenções com as d'Ele."],
  35: ["Mateus 7:7 - \"Pedi, e dar-se-vos-á; buscai, e encontrareis.\"", "Deus deseja ser convidado a participar da sua vida. A oração abre portas que o esforço humano não alcança."],
  36: ["João 15:5 - \"Sem mim nada podeis fazer.\"", "Reconhecer nossa dependência de Deus não é fraqueza, é o segredo para uma vida que realmente dá frutos."],
  37: ["Hebreus 13:8 - \"Jesus Cristo é o mesmo ontem, hoje e para sempre.\"", "Em um mundo de mudanças constantes, você pode ancorar sua vida na imutabilidade de Cristo."],
  38: ["Salmos 27:1 - \"O Senhor é a minha luz e a minha salvação; a quem temerei?\"", "Se a maior força do universo está do seu lado, qualquer oposição se torna pequena."],
  39: ["Provérbios 16:3 - \"Confia ao Senhor as tuas obras, e teus pensamentos serão estabelecidos.\"", "Entregue seus planos a Deus antes de executá-los; Ele alinhará suas ideias à vontade d'Ele."],
  40: ["Romanos 12:2 - \"Não vos conformeis com este mundo...\"", "Não deixe que a cultura dite seus valores. Renove sua mente com a verdade bíblica todos os dias."],
  41: ["Mateus 5:16 - \"Assim brilhe a vossa luz diante dos homens...\"", "Suas boas obras são o rastro de luz que aponta o caminho para Deus aos que estão ao seu redor."],
  42: ["Salmos 40:1 - \"Esperei com paciência pelo Senhor...\"", "A paciência na espera é uma forma de adoração. Deus nunca chega atrasado; Ele chega no momento certo."],
  43: ["Filipenses 4:7 - \"E a paz de Deus... guardará os vossos corações.\"", "A paz de Deus funciona como um sentinela, protegendo suas emoções mesmo quando a lógica diz para se desesperar."],
  44: ["2 Timóteo 1:7 - \"Porque Deus não nos deu espírito de temor...\"", "O medo paralisa, mas o Espírito de Deus nos move com poder, amor e equilíbrio mental."],
  45: ["Salmos 118:24 - \"Este é o dia que o Senhor fez; regozijemo-nos.\"", "Cada dia é um presente único. Não o desperdice lamentando o passado ou temendo o futuro."],
  46: ["Provérbios 15:1 - \"A resposta branda desvia o furor.\"", "Você tem o poder de desarmar um conflito apenas escolhendo palavras gentis em vez de revidar."],
  47: ["João 16:33 - \"No mundo tereis aflições, mas tende bom ânimo.\"", "Jesus não prometeu isenção de problemas, mas garantiu a vitória final sobre eles."],
  48: ["Salmos 55:22 - \"Lança o teu cuidado sobre o Senhor, e ele te susterá.\"", "Deus não prometeu tirar o fardo imediatamente, mas prometeu sustentar você enquanto você o carrega."],
  49: ["Tiago 4:8 - \"Chegai-vos a Deus, e ele se chegará a vós.\"", "A distância entre você e Deus é decidida por você. Dê um passo em direção a Ele hoje."],
  50: ["Eclesiastes 3:1 - \"Tudo tem o seu tempo determinado...\"", "Não tente apressar as estações da sua vida. Há um aprendizado específico para o momento que você vive agora."],
  51: ["Efésios 6:10 - \"Fortalecei-vos no Senhor e na força do seu poder.\"", "Sua própria força tem limite; a força que vem da comunhão com Deus é inesgotável."],
  52: ["Salmos 37:5 - \"Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.\"", "Entregar é um ato de fé; confiar é um ato de descanso. Deixe os resultados nas mãos d'Ele."],
  53: ["1 Coríntios 13:4 - \"O amor é sofredor, é benigno; o amor não é invejoso...\"", "O amor verdadeiro é medido por como tratamos as pessoas que não podem nos oferecer nada em troca."],
  54: ["Salmos 119:11 - \"Escondi a tua palavra no meu coração, para eu não pecar contra ti.\"", "A Bíblia guardada na memória é a melhor defesa contra as escolhas que destroem a nossa paz."],
  55: ["Mateus 6:21 - \"Onde estiver o teu tesouro, aí estará também o teu coração.\"", "O que você mais valoriza (tempo, dinheiro, afeição) revela quem realmente governa sua vida."],
  56: ["2 Coríntios 5:17 - \"Se alguém está em Cristo, nova criatura é.\"", "Seu passado não define mais quem você é. Em Cristo, você tem uma nova identidade e um novo começo."],
  57: ["Salmos 34:18 - \"Perto está o Senhor dos que têm o coração quebrantado.\"", "Deus não ignora sua dor. He se aproxima justamente quando você se sente mais fraco e ferido."],
  58: ["Marcos 9:23 - \"Tudo é possível ao que crê.\"", "A fé remove o rótulo de \"impossível\" das situações, pois coloca Deus na equação."],
  59: ["Colossenses 3:15 - \"E a paz de Cristo... domine em vossos corações.\"", "Deixe que a paz seja o \"juiz\" das suas decisões. Se não há paz, pare e ore um pouco mais."],
  60: ["Salmos 91:1 - \"Aquele que habita no esconderijo do Altíssimo...\"", "Segurança não é a ausência de perigo, mas a presença constante da proteção divina."],
  61: ["Provérbios 18:21 - \"A morte e a vida estão no poder da língua.\"", "Suas palavras podem construir ou destruir. Use sua voz hoje para abençoar e encorajar."],
  62: ["Mateus 18:20 - \"Onde estiverem dois ou três reunidos em meu nome...\"", "Há um poder especial na unidade e na oração feita em conjunto com outros irmãos."],
  63: ["Lucas 1:37 - \"Porque para Deus nada é impossível.\"", "Onde termina o recurso humano, começa a oportunidade para o milagre divino."],
  64: ["Salmos 139:1 - \"Senhor, tu me sondaste e me conheces.\"", "Você nunca é invisível para Deus. Ele conhece suas intenções mais profundas e ama você mesmo assim."],
  65: ["Gálatas 5:22 - \"Mas o fruto do Espírito é: amor, gozo, paz...\"", "O caráter cristão não é um esforço humano, mas o resultado natural de estar ligado a Deus."],
  66: ["Sofonias 3:17 - \"O Senhor teu Deus... se deleitará em ti com alegria.\"", "Deus não apenas te aceita; Ele se alegra em você. Sinta o prazer do Pai sobre sua vida hoje."],
  67: ["1 João 5:4 - \"E esta é a vitória que vence o mundo, a nossa fé.\"", "A fé nos permite enxergar além das circunstâncias temporais e focar na eternidade."],
  68: ["Salmos 28:7 - \"O Senhor é a minha força e o meu escudo.\"", "Proteção e vigor caminham juntos. Deus não apenas te defende, Ele te fortalece para lutar."],
  69: ["Tiago 1:19 - \"Todo homem seja pronto para ouvir, tardio para falar.\"", "A sabedoria muitas vezes mora no silêncio e na capacidade de compreender o outro antes de julgar."],
  70: ["Romanos 15:13 - \"O Deus de esperança vos encha de todo o gozo e paz.\"", "A esperança cristã não é um desejo positivo, é uma âncora segura que traz alegria real."],
  71: ["Mateus 7:12 - \"Tudo o que vós quereis que os homens vos façam, fazei-lho também vós.\"", "A regra de ouro simplifica a vida: trate o próximo com a mesma graça que você deseja receber."],
  72: ["Salmos 147:3 - \"Sara os quebrantados de coração e liga-lhes as feridas.\"", "Deus é o médico da alma. Não esconda sua dor d'Ele; permita que Ele cure o que está ferido."],
  73: ["Provérbios 16:9 - \"O coração do homem planeja o seu caminho, mas o Senhor lhe dirige os passos.\"", "Planeje com dedicação, mas deixe a última palavra e o ajuste final para o comando de Deus."],
  74: ["1 Pedro 2:9 - \"Vós sois a geração eleita... para que anuncieis as virtudes...\"", "Você tem um propósito: refletir o caráter de Deus no lugar onde Ele te plantou hoje."],
  75: ["Salmos 32:8 - \"Instruir-te-ei e ensinar-te-ei o caminho que deves seguir.\"", "A direção divina é personalizada. Ele promete guiar seus olhos para que você não se desvie."],
  76: ["2 Coríntios 4:16 - \"Ainda que o nosso homem exterior se corrompa, o interior se renova.\"", "O tempo pode desgastar o corpo, mas a comunhão com Deus rejuvenesce o espírito diariamente."],
  77: ["Filipenses 2:14 - \"Fazei todas as coisas sem murmurações nem contendas.\"", "A reclamação afasta a gratidão. Experimente enfrentar o dia de hoje sem se queixar de nada."],
  78: ["Salmos 62:1 - \"A minha alma descansa somente em Deus; dele vem a minha salvação.\"", "Há um nível de descanso que só é alcançado quando paramos de buscar soluções em homens."],
  79: ["Habacuque 3:17-18 - \"Ainda que a figueira não floresça... eu me alegrarei no Senhor.\"", "Sua alegria deve estar na fonte (Deus), e não apenas nos frutos (bênçãos)."],
  80: ["João 10:10 - \"Eu vim para que tenham vida, e a tenham com abundância.\"", "Vida abundante não é falta de problemas, é plenitude de sentido e presença divina no cotidiano."],
  81: ["Provérbios 22:1 - \"Mais vale o bom nome do que as muitas riquezas.\"", "Sua integridade é seu maior patrimônio. Dinheiro se recupera, o caráter é construído dia a dia."],
  82: ["Colossenses 3:2 - \"Pensai nas coisas que são de cima, e não nas que são da terra.\"", "Eleve sua perspectiva. Problemas terrenos parecem menores quando olhados sob a ótica da eternidade."],
  83: ["Salmos 119:165 - \"Muita paz têm os que amam a tua lei.\"", "A obediência aos princípios de Deus é o caminho mais curto para uma consciência tranquila."],
  84: ["Hebreus 4:16 - \"Cheguemo-nos, pois, confiadamente ao trono da graça.\"", "Você tem acesso direto ao Rei. Não hesite em levar suas necessidades diante d'Ele hoje."],
  85: ["Mateus 5:9 - \"Bem-aventurados os pacificadores...\"", "Ser pacificador é diferente de ser passivo; é trabalhar ativamente para restaurar relacionamentos."],
  86: ["Salmos 56:3 - \"No dia em que eu temer, hei de confiar em ti.\"", "O medo é uma emoção, a confiança é uma decisão. Escolha confiar quando o susto vier."],
  87: ["Efésios 2:8 - \"Porque pela graça sois salvos, por meio da fé.\"", "Você não precisa merecer o amor de Deus; você só precisa aceitar o presente que Ele já deu."],
  88: ["Provérbios 17:17 - \"Em todo o tempo ama o amigo; e na angústia nasce o irmão.\"", "Valorize quem permanece ao seu lado quando o cenário não é favorável. Seja você também esse amigo."],
  89: ["Lucas 6:38 - \"Dai, e ser-vos-á dado...\"", "A generosidade abre portas. O que você planta na vida dos outros, Deus retribui na sua."],
  90: ["Salmos 30:5 - \"O choro pode durar uma noite, mas a alegria vem pela manhã.\"", "Nenhuma temporada difícil é eterna. Aguente firme, o sol da justiça está prestes a nascer."],
  91: ["Romanos 12:21 - \"Não te deixes vencer pelo mal, mas vence o mal com o bem.\"", "Retribuir o mal com o mal é se igualar; retribuir com o bem é demonstrar a força de Cristo."],
  92: ["Mateus 6:12 - \"Perdoa-nos as nossas dívidas, assim como nós perdoamos...\"", "O perdão é a chave da liberdade. Não prende ninguém em uma dívida que Deus já pagou por você."],
  93: ["Salmos 126:5 - \"Os que semeiam em lágrimas segarão com alegria.\"", "Às vezes, o trabalho é duro e sofrido, mas o resultado final valerá cada gota de suor."],
  94: ["1 Coríntios 10:13 - \"Deus é fiel, e não vos deixará tentar acima do que podeis.\"", "A provação nunca é maior que a estrutura que Deus te deu para suportá-la. Há sempre uma saída."],
  95: ["Tiago 1:12 - \"Bem-aventurado o homem que sofre a tentação...\"", "Resistir ao erro fortalece o espírito e prepara você para receber a \"coroa da vida\"."],
  96: ["Salmos 116:12 - \"Que darei eu ao Senhor, por todos os seus benefícios para comigo?\"", "A melhor resposta aos favores de Deus é uma vida de gratidão e serviço ao próximo."],
  97: ["Filipenses 1:6 - \"Aquele que em vós começou a boa obra a aperfeiçoará.\"", "Deus não deixa projetos inacabados. He ainda está trabalhando em você, tenha paciência."],
  98: ["Salmos 33:11 - \"Os planos do Senhor permanecem para sempre.\"", "Enquanto os planos humanos falham e mudam, a vontade de Deus é sólida e eterna."],
  99: ["Marcos 11:24 - \"Tudo o que pedirdes, orando, crede que o recebereis.\"", "A oração acompanhada de fé é o combustível que move o impossível."],
  100: ["Salmos 100:2 - \"Servi ao Senhor com alegria.\"", "Servir não deve ser um peso, mas uma resposta alegre ao amor que recebemos de Deus."],
  101: ["Provérbios 14:1 - \"A mulher sábia edifica a sua casa.\"", "Sabedoria é a habilidade de construir relacionamentos saudáveis e um lar de paz."],
  102: ["Isaías 26:3 - \"Tu conservarás em paz aquele cujo pensamento é firme em ti.\"", "O segredo da estabilidade emocional é manter o foco na presença de Deus, não nos problemas."],
  103: ["Mateus 5:7 - \"Bem-aventurados os misericordiosos.\"", "Mostre aos outros a mesma compaixão que Deus estende a você todos os dias."],
  104: ["Romanos 8:31 - \"Se Deus é por nós, quem será contra nós?\"", "A oposição pode ser barulhenta, mas a proteção de Deus é invencível e silenciosa."],
  105: ["Salmos 119:18 - \"Abre os meus olhos para que veja as maravilhas da tua lei.\"", "Peça a Deus uma visão espiritual hoje; há beleza escondida nas coisas simples que Ele criou."],
  106: ["2 Coríntios 9:7 - \"Deus ama ao que dá com alegria.\"", "Generosidade não é sobre o valor, mas sobre a disposição do coração em abençoar o próximo."],
  107: ["Hebreus 12:1 - \"Deixemos todo o embaraço e corramos com paciência.\"", "Identifique o que está te atrasando na vida espiritual e escolha soltar esse peso hoje."],
  108: ["Salmos 37:7 - \"Descansa no Senhor e espera nele.\"", "Esperar não é passividade; é um ato de confiança ativa de que Deus está agindo nos bastidores."],
  109: ["Tiago 1:22 - \"Sede cumpridores da palavra e não somente ouvintes.\"", "O conhecimento bíblico só transforma a vida quando é colocado em prática na rotina."],
  110: ["João 14:6 - \"Eu sou o caminho, a verdade e a vida.\"", "Em um mundo cheio de opiniões e direções confusas, Jesus é o único norte seguro."],
  111: ["Salmos 19:14 - \"Sejam agradáveis as palavras da minha boca...\"", "Que seus diálogos de hoje sejam como um bálsamo para quem os ouve."],
  112: ["Efésios 5:16 - \"Remindo o tempo, porquanto os dias são maus.\"", "O tempo é o seu recurso mais precioso. Use-o para o que realmente tem valor eterno."],
  113: ["1 João 4:19 - \"Nós o amamos porque ele nos amou primeiro.\"", "O nosso amor por Deus é apenas um eco do imenso amor que Ele já demonstrou por nós."],
  114: ["Salmos 34:7 - \"O anjo do Senhor acampa-se ao redor dos que o temem.\"", "Você nunca está desprotegido. Há um exército invisível cuidando dos seus passos."],
  115: ["Provérbios 27:17 - \"Como o ferro com o ferro se afia, assim o homem ao seu amigo.\"", "Relacionamentos saudáveis nos desafiam a crescer e a sermos pessoas melhores."],
  116: ["Mateus 28:20 - \"E eis que eu estou convosco todos os dias.\"", "A solidão é uma mentira; a presença de Cristo é uma promessa contínua para você."],
  117: ["Salmos 63:1 - \"Ó Deus, a minha alma tem sede de ti.\"", "Nada neste mundo pode preencher o vazio que só o Criador consegue ocupar."],
  118: ["Colossenses 4:6 - \"A vossa palavra seja sempre agradável, temperada com sal.\"", "Fale com graça. O tom da sua voz pode abrir ou fechar portas no coração das pessoas."],
  119: ["1 Pedro 5:6 - \"Humilhai-vos sob a potente mão de Deus...\"", "Reconhecer sua pequenez diante de Deus é o primeiro passo para ser exaltado por Ele."],
  120: ["Salmos 27:14 - \"Espera no Senhor, anima-te, e ele fortalecerá o teu coração.\"", "O tempo de espera é o ginásio de Deus para fortalecer o seu caráter."],
  121: ["Mateus 6:14 - \"Se perdoardes aos homens as suas ofensas, vosso Pai vos perdoará.\"", "O perdão é a higiene da alma. Não deixe o lixo do rancor acumular dentro de você."],
  122: ["Salmos 119:9 - \"Como purificará o jovem o seu caminho? Observando a tua palavra.\"", "A pureza não é natural; ela é mantida através do contato constante com a verdade bíblica."],
  123: ["2 Timóteo 4:7 - \"Combati o bom combate, acabei a carreira, guardei a fé.\"", "O objetivo não é chegar primeiro, mas terminar o dia tendo mantido a integridade."],
  124: ["Salmos 34:4 - \"Busquei ao Senhor, e ele me acolheu; livrou-me de todos os meus temores.\"", "A oração é o antídoto mais eficaz contra o medo e a insegurança."],
  125: ["Eclesiastes 4:9 - \"Melhor é serem dois do que um.\"", "Não tente carregar o mundo sozinho. Deus criou a comunidade para que nos apoiemos."],
  126: ["João 16:24 - \"Pedi e recebereis, para que o vosso gozo se cumpra.\"", "Deus tem prazer em atender os pedidos que trazem alegria e glória ao Reino d'Ele."],
  127: ["Salmos 42:11 - \"Por que estás abatida, ó minha alma? Espera em Deus.\"", "Pregue para si mesmo: lembre sua alma de que Deus ainda está no trono e agirá."],
  128: ["Salmos 121:2 - \"O meu socorro vem do Senhor, que fez o céu e a terra.\"", "Se Aquele que sustenta o universo está cuidando de você, o seu problema não é grande demais para Ele."],
  129: ["Provérbios 3:6 - \"Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.\"", "Convide Deus para as decisões triviais, não apenas para as grandes crises."],
  130: ["Mateus 5:8 - \"Bem-aventurados os limpos de coração, porque eles verão a Deus.\"", "A pureza de intenção limpa as lentes da alma para enxergarmos a presença de Deus em tudo."],
  131: ["Romanos 8:1 - \"Portanto, agora nenhuma condenação há para os que estão em Cristo.\"", "Se Deus já te perdoou, pare de se punir por erros que o Sangue de Jesus já apagou."],
  132: ["Salmos 46:1 - \"Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.\"", "Você não precisa procurar Deus; Ele já está presente, pronto para ser seu abrigo no meio da tempestade."],
  133: ["Lucas 6:31 - \"Como quereis que os homens vos façam, da mesma maneira fazei-lhes vós.\"", "A empatia é o evangelho em ação. Coloque-se no lugar do outro antes de agir hoje."],
  134: ["Filipenses 4:19 - \"O meu Deus, segundo as suas riquezas, suprirá todas as vossas necessidades.\"", "Deus supre o que você precisa, que nem sempre é o que você quer, mas é sempre o que é melhor para você."],
  135: ["Tiago 1:17 - \"Toda a boa dádiva... vem do alto, descendo do Pai das luzes.\"", "Olhe ao seu redor e agradeça pelas \"pequenas\" coisas; cada detalhe bom da sua vida é um presente divino."],
  136: ["Salmos 37:23 - \"Os passos de um homem bom são confirmados pelo Senhor.\"", "Siga em frente com confiança; se o seu coração é íntegro, Deus está guiando cada pisada sua."],
  137: ["Efésios 4:26 - \"Não se ponha o sol sobre a vossa ira.\"", "O rancor é um veneno que você toma esperando que o outro morra. Resolva as mágoas antes de dormir."],
  138: ["João 14:1 - \"Não se turbe o vosso coração; credes em Deus, crede também em mim.\"", "A perturbação é o ruído do medo; a fé é o silêncio da confiança. Escolha a fé hoje."],
  139: ["1 Tessalonicenses 5:17 - \"Orai sem cessar.\"", "Manter uma conversa constante com Deus transforma o seu dia comum em um lugar sagrado."],
  140: ["Salmos 119:114 - \"Tu és o meu refúgio e o meu escudo; espero na tua palavra.\"", "Quando o mundo estiver barulhento, esconda-se nas promessas das Escrituras."],
  141: ["Provérbios 10:22 - \"A bênção do Senhor é que enriquece; e não traz consigo dores.\"", "O que vem de Deus traz paz e construção, não ansiedade e destruição."],
  142: ["Mateus 11:29 - \"Tomai sobre vós o meu jugo... e achareis descanso.\"", "O jugo de Jesus é o aprendizado. Quanto mais aprendemos com Ele, mais leve a vida fica."],
  143: ["Salmos 9:10 - \"Os que conhecem o teu nome confiam em ti.\"", "Conhecer a Deus é o único remédio para a insegurança. Busque intimidade com Ele hoje."],
  144: ["Gálatas 6:2 - \"Levai as cargas uns dos outros e assim cumprieis a lei de Cristo.\"", "Hoje, tente ser o ombro amigo ou a mão que ajuda alguém a carregar um fardo pesado."],
  145: ["Isaías 43:2 - \"Quando passares pelas águas estarei contigo.\"", "Deus não prometeu que não haveria rios difíceis, mas prometeu que você não morreria afogado neles."],
  146: ["Hebreus 13:5 - \"Não te deixarei, nem te desampararei.\"", "Esta é a garantia máxima: em nenhum momento do seu dia você estará entregue à própria sorte."],
  147: ["Salmos 34:1 - \"Louvarei ao Senhor em todo o tempo.\"", "O louvor não depende do seu humor, mas da fidelidade de Deus, que nunca muda."],
  148: ["Colossenses 3:17 - \"Tudo o que fizerdes... fazei-o em nome do Senhor Jesus.\"", "Transforme suas tarefas domésticas ou profissionais em um culto a Deus através da excelência."],
  149: ["Mateus 5:44 - \"Amai a vossos inimigos, bendizei os que vos maldizem.\"", "Amar quem nos ama é fácil; amar quem nos fere é o que nos torna parecidos com Jesus."],
  150: ["Salmos 23:3 - \"Refrigera a minha alma; guia-me pelas veredas da justiça.\"", "Quando o mundo te cansa, o Bom Pastor restaura suas forças emocionais e mentais."],
  151: ["1 João 3:18 - \"Não amemos de palavra... mas por obra e em verdade.\"", "O amor é um verbo de ação. Deixe que suas atitudes falem mais alto que seu discurso hoje."],
  152: ["Provérbios 13:20 - \"Quem anda com os sábios será sábio.\"", "Escolha bem suas companhias. Elas moldam sua mentalidade e o seu futuro."],
  153: ["2 Coríntios 3:17 - \"Onde está o Espírito do Senhor, aí há liberdade.\"", "A verdadeira liberdade não é fazer o que se quer, mas ser livre do que nos escraviza por dentro."],
  154: ["Salmos 119:50 - \"Isto é a minha consolação na minha aflição: que a tua palavra me vivificou.\"", "Quando faltarem forças, abra a Bíblia; as palavras de Deus têm poder de ressuscitar a esperança."],
  155: ["Marcos 10:27 - \"Para Deus tudo é possível.\"", "Não coloque limites humanos no agir divino. Ele trabalha fora da nossa lógica."],
  156: ["Efésios 4:2 - \"Com toda a humildade e mansidão, com longanimidade, suportando-vos uns aos outros.\"", "Relacionamentos exigem paciência. Hoje, escolha suportar com amor aquela pessoa difícil."],
  157: ["Salmos 143:8 - \"Faze-me ouvir a tua benignidade pela manhã, pois em ti confio.\"", "Consagre as primeiras horas do seu dia a Deus e o restante do dia terá o ritmo d'Ele."],
  158: ["Salmos 119:160 - \"A tua palavra é a verdade desde o princípio.\"", "Em uma era de incertezas e notícias falsas, a Bíblia permanece como a única rocha inabalável."],
  159: ["Mateus 5:13 - \"Vós sois o sal da terra.\"", "O sal preserva e dá sabor. Sua função hoje é impedir que o ambiente se corrompa e trazer o sabor da esperança."],
  160: ["Provérbios 19:21 - \"Muitos propósitos há no coração do homem, mas o desígnio do Senhor permanecerá.\"", "Descanse no fato de que, mesmo quando seus planos falham, o propósito soberano de Deus continua avançando."],
  161: ["Romanos 12:12 - \"Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração.\"", "Três chaves para um dia difícil: olhar para o futuro com fé, aguentar o presente com calma e falar com o Pai sem parar."],
  162: ["Salmos 37:25 - \"Fui moço, e agora sou velho; mas nunca vi desamparado o justo.\"", "A fidelidade de Deus tem um histórico impecável. Ele não vai começar a falhar justamente com você."],
  163: ["Efésios 4:31 - \"Toda a amargura, e ira, e cólera... sejam tiradas dentre vós.\"", "A amargura é um entulho na alma. Peça a Deus ajuda para fazer uma limpeza interna hoje."],
  164: ["1 João 4:16 - \"Deus é amor; e quem está em amor está em Deus.\"", "O amor não é apenas um atributo de Deus, é a essência d'Ele. Viver em amor é viver na presença d'Ele."],
  165: ["Salmos 145:18 - \"Perto está o Senhor de todos os que o invocam.\"", "A oração não precisa de palavras difíceis, apenas de um coração que chama com sinceridade."],
  166: ["Mateus 6:26 - \"Olhai para as aves do céu... o vosso Pai celestial as alimenta.\"", "Se Deus cuida de criaturas tão pequenas, por que Ele esqueceria de você, que é filho(a)?"],
  167: ["Provérbios 16:32 - \"Melhor é o que tarda em irar-se do que o que toma uma cidade.\"", "O maior sinal de força não é dominar os outros, mas ter o domínio próprio sobre as suas reações."],
  168: ["João 3:16 - \"Porque Deus amou o mundo de tal maneira que deu o seu Filho...\"", "O valor de algo é medido pelo preço pago. Você custou o sangue de Cristo; você tem um valor infinito."],
  169: ["Salmos 51:17 - \"A um coração quebrantado e contrito não desprezarás, ó Deus.\"", "Deus não procura perfeição, Ele procura um coração honesto que reconhece que precisa d'Ele."],
  170: ["Filipenses 4:11 - \"Aprendi a contentar-me com o que tenho.\"", "O contentamento não é ter tudo o que se quer, mas encontrar satisfação na presença de Deus, independente do que se tem."],
  171: ["Colossenses 3:13 - \"Suportai-vos uns aos outros e perdoai-vos mutuamente.\"", "O perdão é o óleo que impede que as engrenagens da convivência humana travem."],
  172: ["Salmos 121:4 - \"Eis que não tosquenejará nem dormirá o guarda de Israel.\"", "Você pode dormir em paz, pois Quem te guarda não precisa de descanso e está vigiando agora."],
  173: ["Lucas 12:15 - \"A vida de qualquer um não consiste na abundância do que possui.\"", "Não defina seu sucesso pelo que está na sua conta, mas por quem você é diante de Deus."],
  174: ["1 Coríntios 15:58 - \"Sede firmes e constantes... o vosso trabalho não é vão.\"", "Nada do que você faz para Deus é desperdiçado, mesmo que ninguém veja ou agradeça agora."],
  175: ["Salmos 25:4 - \"Faze-me saber os teus caminhos, Senhor; ensina-me as tuas veredas.\"", "Comece o dia pedindo um mapa espiritual. Deixe Deus ser o seu GPS em cada conversa e decisão."],
  176: ["Mateus 10:30 - \"Até os cabelos da vossa cabeça estão todos contados.\"", "Deus conhece os detalhes mais irrelevantes da sua vida. Nada do que te preocupa passa despercebido por Ele."],
  177: ["Hebreus 10:23 - \"Retenhamos firmes a confissão da nossa esperança... pois fiel é o que prometeu.\"", "A sua esperança não se baseia na sua força, mas na fidelidade dAquele que fez a promessa."],
  178: ["Salmos 119:130 - \"A exposição das tuas palavras dá luz; dá entendimento aos simples.\"", "Ler a Bíblia clareia a mente. Se você está confuso, mergulhe na Palavra para encontrar lucidez."],
  179: ["Tiago 4:7 - \"Sujeitai-vos, pois, a Deus, resisti ao diabo, e ele fugirá de vós.\"", "A resistência começa com a rendição. Renda-se ao governo de Deus e você terá autoridade para vencer o mal."],
  180: ["2 Coríntios 5:7 - \"Porque andamos por fé, e não por vista.\"", "Nem sempre o que vemos ao redor é bom, mas o que sabemos sobre Deus é o que nos mantém caminhando."],
  181: ["Salmos 37:1 - \"Não te indignes por causa dos malfeitores.\"", "Não perca sua paz olhando para a injustiça alheia. Foque no seu caminho com o Senhor."],
  182: ["Provérbios 12:25 - \"A ansiedade no coração abate o homem, mas uma boa palavra o alegra.\"", "Seja hoje a pessoa que leva a \"boa palavra\". Um elogio ou encorajamento pode mudar o dia de alguém."],
  183: ["João 15:15 - \"Já não vos chamo servos... chamei-vos amigos.\"", "Imagine o privilégio: o Criador do universo te convida para uma relação de amizade íntima."],
  184: ["Salmos 107:1 - \"Louvai ao Senhor, porque ele é bom; porque a sua misericórdia dura para sempre.\"", "A misericórdia de Deus é como um rio que nunca seca. Se você falhou ontem, mergulhe nela hoje."],
  185: ["Gálatas 5:1 - \"Estai, pois, firmes na liberdade com que Cristo nos libertou.\"", "Não volte a ser escravo de vícios, culpas ou medos dos quais Jesus já te tirou."],
  186: ["Salmos 119:10 - \"De todo o meu coração te busquei; não me deixes desviar dos teus mandamentos.\"", "A busca sincera por Deus é a nossa melhor proteção contra os desvios da vida."],
  187: ["Romanos 8:38-39 - \"Nada nos poderá separar do amor de Deus.\"", "Nem a morte, nem a vida, nem o presente, nem o futuro. Você está seguro no abraço eterno de Deus."],
  188: ["Salmos 119:71 - \"Foi-me bom ter sido afligido, para que aprendesse os teus estatutos.\"", "Às vezes, a dor é a sala de aula onde aprendemos lições que o conforto jamais ensinaria."],
  189: ["Provérbios 3:27 - \"Não detenhas o bem de quem o merece, estando na tua mão o poder de fazê-lo.\"", "Se você pode ajudar alguém hoje, não adie. A oportunidade de ser um canal de Deus é um privilégio."],
  190: ["Mateus 6:19-20 - \"Não ajunteis tesouros na terra... mas ajunteis tesouros no céu.\"", "Invista em pessoas, em caráter e em amor. Essas são as únicas moedas que valem na eternidade."],
  191: ["Isaías 40:29 - \"Dá força ao cansado, e multiplica as forças ao que não tem nenhum vigor.\"", "Quando suas baterias acabarem, lembre-se: Deus é a fonte de energia que não depende do seu descanso físico."],
  192: ["Salmos 4:8 - \"Em paz também me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança.\"", "O sono tranquilo é um presente para quem confia que o mundo continua nas mãos de Deus enquanto dormimos."],
  193: ["Tiago 1:2 - \"Meus irmãos, tende grande gozo quando cairdes em várias tentações [provações].\"", "A prova não vem para te destruir, mas para testar e aprovar a resistência da sua fé."],
  194: ["Romanos 12:15 - \"Alegrai-vos com os que se alegram; e chorai com os que choram.\"", "A empatia cristã nos convida a sair do nosso próprio umbigo para carregar o sentimento do próximo."],
  195: ["Salmos 119:37 - \"Desvia os meus olhos de contemplarem a vaidade.\"", "Peça a Deus foco. Não perca tempo comparando sua vida com as ilusões que o mundo exibe."],
  196: ["2 Coríntios 4:7 - \"Temos, porém, este tesouro em vasos de barro...\"", "Somos frágeis e imperfeitos, mas carregamos dentro de nós a presença gloriosa do próprio Deus."],
  197: ["Mateus 7:24 - \"Todo aquele que ouve estas minhas palavras e as pratica, será comparado ao homem sábio...\"", "A base da sua vida é o que você faz com o que ouve de Jesus. Construa sobre a rocha da obediência."],
  198: ["Salmos 138:8 - \"O Senhor aperfeiçoará o que me concerne.\"", "Deus cuida dos seus interesses. He está polindo cada detalhe da sua história agora mesmo."],
  199: ["Provérbios 21:2 - \"Todo caminho do homem é reto aos seus olhos, mas o Senhor sonda os corações.\"", "Mais importante do que o que você faz, é o porquê você faz. Deus olha a intenção."],
  200: ["João 11:25 - \"Eu sou a ressurreição e a vida; quem crê em mim, ainda que esteja morto, viverá.\"", "Em Cristo, nem mesmo a morte tem a última palavra. Temos a esperança da vida eterna."],
  201: ["Salmos 147:5 - \"Grande é o nosso Senhor... o seu entendimento é infinito.\"", "Não tente entender Deus com sua mente limitada. Apenas confie na sabedoria infinita d'Ele."],
  202: ["Filipenses 2:3 - \"Nada façais por contenda ou por vanglória...\"", "A humildade é considerar que os outros também têm valores e necessidades importantes."],
  203: ["Colossenses 3:14 - \"E, sobre tudo isto, revesti-vos de amor, que é o vínculo da perfeição.\"", "O amor é o \"acabamento\" final de todas as nossas atitudes. Sem ele, nada faz sentido."],
  204: ["Salmos 37:8 - \"Deixa a ira, e abandona o furor; não te indignes para fazer o mal.\"", "A raiva é um incêndio. Não alimente as chamas; peça a Deus o orvalho da calma."],
  205: ["1 Pedro 3:15 - \"Estai sempre preparados para responder... a razão da esperança que há em vós.\"", "Sua vida deve ser tão diferente que as pessoas sintam curiosidade sobre a fonte da sua paz."],
  206: ["Mateus 5:6 - \"Bem-aventurados os que têm fome e sede de justiça.\"", "Deseje as coisas certas e Deus prometerá que você será plenamente satisfeito."],
  207: ["Salmos 119:45 - \"E andarei em liberdade; pois busquei os teus preceitos.\"", "A verdadeira liberdade é encontrada dentro dos limites protetores da vontade de Deus."],
  208: ["Lamentações 3:25 - \"Bom é o Senhor para os que esperam por ele, para a alma que o busca.\"", "A espera nunca é vã quando o objeto da nossa busca é a face de Deus."],
  209: ["Provérbios 4:18 - \"A vereda dos justos é como a luz da aurora, que vai brilhando mais e mais...\"", "Sua caminhada com Deus não deve estagnar; ela deve ser progressiva e cada vez mais clara."],
  210: ["Hebreus 12:2 - \"Olhando para Jesus, autor e consumador da fé.\"", "Se você olhar para os lados, se distrai; se olhar para baixo, desanima; olhe para Jesus e siga."],
  211: ["Salmos 119:111 - \"Os teus testemunhos tenho eu tomado por herança para sempre.\"", "As promessas bíblicas são o seu patrimônio espiritual. Tome posse delas hoje."],
  212: ["Efésios 4:29 - \"Não saia da vossa boca nenhuma palavra torpe, mas só a que for boa para promover a edificação.\"", "Suas palavras são sementes. Escolha plantar vida na mente de quem te ouve."],
  213: ["1 João 5:14 - \"Esta é a confiança... que, se pedirmos alguma coisa, segundo a sua vontade, ele nos ouve.\"", "A oração eficaz é aquela que busca o que Deus já deseja nos dar."],
  214: ["Salmos 31:15 - \"Os meus tempos estão nas tuas mãos.\"", "O cronômetro da sua vida não está quebrado; ele está sendo segurado pelo Criador do tempo."],
  215: ["Romanos 14:17 - \"Porque o reino de Deus não é comida nem bebida, mas justiça, e paz, e alegria no Espírito Santo.\"", "Não foque apenas no material. Busque o que traz satisfação real ao espírito."],
  216: ["2 Coríntios 1:3-4 - \"O Deus de toda a consolação... nos consola em toda a nossa tribulação.\"", "Deus te consola para que você se torne um especialista em consolar outros que sofrem."],
  217: ["Salmos 119:133 - \"Firma os meus passos na tua palavra.\"", "Peça estabilidade. Que as flutuações do mundo não abalem a sua firmeza em Cristo."],
  218: ["Salmos 119:103 - \"Quão doces são as tuas palavras ao meu paladar!\"", "A Bíblia não é apenas um manual de regras, é o alimento que traz prazer e sustento à alma cansada."],
  219: ["Mateus 6:8 - \"Vosso Pai sabe o que vos é necessário, antes que vós lho peçais.\"", "Ore não para informar a Deus, mas para se conectar com Aquele que já conhece e cuida de tudo."],
  220: ["Provérbios 14:29 - \"O que é tardio em irar-se é grande em entendimento.\"", "A paciência é a prova máxima de que você compreende a graça que Deus tem com você."],
  221: ["1 Coríntios 16:14 - \"Todas as vossas coisas sejam feitas com amor.\"", "O amor deve ser o ingrediente principal, desde o café da manhã até o fechamento de um grande negócio."],
  222: ["Salmos 51:12 - \"Restitui-me a alegria da tua salvação.\"", "Se você perdeu o entusiasmo pela fé, peça a Deus hoje para reacender a chama do primeiro amor."],
  223: ["Tiago 1:17 - \"Em quem não há mudança nem sombra de variação.\"", "Pessoas mudam, sentimentos oscilam, mas o caráter e o amor de Deus são constantes e imutáveis."],
  224: ["Romanos 8:37 - \"Em todas estas coisas somos mais do que vencedores, por aquele que nos amou.\"", "Vencer não é não ter problemas, é passar por eles sem perder a fé e o propósito."],
  225: ["Salmos 119:112 - \"Inclinei o meu coração a guardar os teus estatutos.\"", "A obediência começa com uma inclinação da vontade. Decida hoje seguir os princípios de Deus."],
  226: ["Mateus 5:5 - \"Bem-aventurados os mansos, porque eles herdarão a terra.\"", "A mansidão não é fraqueza, é o poder sob controle. É saber que Deus luta as suas guerras."],
  227: ["Efésios 5:20 - \"Dando sempre graças por tudo a nosso Deus e Pai.\"", "A gratidão contínua blinda o coração contra a murmuração e a inveja."],
  228: ["Provérbios 3:7 - \"Não sejas sábio a teus próprios olhos.\"", "Mantenha o coração ensinável. Há sempre algo novo que Deus quer te mostrar através de outras pessoas."],
  229: ["Salmos 91:2 - \"Direi do Senhor: Ele é o meu refúgio e a minha fortaleza.\"", "Não guarde a fé apenas para si; declare a sua confiança em Deus e fortaleça outros."],
  230: ["João 14:27 - \"Não se turbe o vosso coração, nem se atemorize.\"", "A paz de Cristo é um escudo. Se o mundo está em guerra, seu interior pode continuar em repouso."],
  231: ["Filipenses 3:13 - \"Esquecendo-me das coisas que atrás ficam e avançando para as que estão diante de mim.\"", "Não deixe que os erros do passado sejam âncoras que te impedem de navegar rumo ao futuro."],
  232: ["Salmos 119:66 - \"Ensina-me bom juízo e conhecimento.\"", "Peça a Deus discernimento para distinguir o que é urgente do que é realmente importante."],
  233: ["1 Pedro 4:8 - \"O amor cobrirá uma multidão de pecados.\"", "Onde há amor, há espaço para a restauração. Seja alguém que restaura, não que expõe as falhas alheias."],
  234: ["Salmos 18:30 - \"O caminho de Deus é perfeito; a palavra do Senhor é provada.\"", "Você pode não entender o caminho agora, mas pode confiar na perfeição de quem o desenhou."],
  235: ["Mateus 7:1 - \"Não julgueis, para que não sejais julgados.\"", "Antes de apontar o erro do próximo, lembre-se da paciência que Deus tem com as suas próprias falhas."],
  236: ["Colossenses 3:12 - \"Revesti-vos de entranhas de misericórdia, de benignidade...\"", "Escolha suas \"roupas espirituais\" hoje: vista-se de bondade e humildade logo cedo."],
  237: ["Salmos 119:147 - \"Antecipei a alva da manhã e clamei; esperei na tua palavra.\"", "Falar com Deus antes de falar com o mundo coloca o seu dia na perspectiva correta."],
  238: ["2 Coríntios 12:10 - \"Porque quando estou fraco então sou forte.\"", "Sua fraqueza é a oportunidade para o poder de Deus se manifestar. Não se envergonhe de precisar d'Ele."],
  239: ["Provérbios 15:13 - \"O coração alegre aformoseia o rosto.\"", "A verdadeira beleza vem de uma alma que encontrou descanso e alegria na presença do Criador."],
  240: ["Mateus 18:21-22 - \"Até setenta vezes sete.\"", "O perdão não é um sentimento, é uma decisão matemática de não cobrar mais a dívida do outro."],
  241: ["Salmos 119:162 - \"Folgo com a tua palavra, como aquele que acha um grande despojo.\"", "Trate a leitura bíblica como quem encontra um tesouro escondido todos os dias."],
  242: ["Hebreus 13:16 - \"Não vos esqueçais da beneficência e comunicação.\"", "Fazer o bem e compartilhar o que você tem são sacrifícios que agradam profundamente a Deus."],
  243: ["João 15:4 - \"Estai em mim, e eu em vós.\"", "A vida cristã não é sobre esforço, é sobre conexão. Permaneça ligado à Videira e os frutos virão."],
  244: ["Salmos 139:23 - \"Sonda-me, ó Deus, e conhece o meu coração.\"", "Permita que Deus faça um \"check-up\" na sua alma hoje para remover o que não deveria estar lá."],
  245: ["Gálatas 5:25 - \"Se vivemos no Espírito, andemos também no Espírito.\"", "Que a sua caminhada prática seja coerente com a fé que você professa ter."],
  246: ["Salmos 119:105 - \"Lâmpada para os meus pés é a tua palavra.\"", "Ela ilumina onde você pisa agora, para que você não tropece no escuro das incertezas."],
  247: ["2 Timóteo 2:1 - \"Fortifica-te na graça que há em Cristo Jesus.\"", "A graça não serve apenas para te salvar, ela serve para te dar forças para viver o dia de hoje."],
  248: ["Salmos 119:165 - \"Grande paz têm os que amam a tua lei; para eles não há tropeço.\"", "O amor pelos princípios de Deus funciona como um amortecedor para as pancadas da vida."],
  249: ["Provérbios 20:24 - \"Os passos do homem são dirigidos pelo Senhor.\"", "Se você entregou seu dia a Deus, não se assuste com os desvios; Ele sabe o caminho melhor que você."],
  250: ["Mateus 5:48 - \"Sede vós pois perfeitos, como é perfeito o vosso Pai...\"", "Perfeição aqui é maturidade. Busque crescer um pouco mais hoje em amor e integridade."],
  251: ["Romanos 5:1 - \"Tendo sido, pois, justificados pela fé, temos paz com Deus.\"", "A guerra acabou. Através de Jesus, você não é mais inimigo de Deus, mas herdeiro e amigo."],
  252: ["Salmos 37:3 - \"Confia no Senhor e faze o bem; habitarás na terra, e verdadeiramente serás alimentado.\"", "A confiança em Deus deve ser acompanhada por ações corretas. Faça a sua parte e Ele fará a d'Ele."],
  253: ["Tiago 1:12 - \"Bem-aventurado o homem que suporta a provação.\"", "A resistência produz um caráter aprovado. O que te aperta hoje está te fortalecendo para o amanhã."],
  254: ["Filipenses 4:8 - \"Tudo o que é verdadeiro... nisso pensai.\"", "Sua mente é um jardim. Não deixe as ervas daninhas da mentira e do pessimismo crescerem."],
  255: ["Salmos 119:116 - \"Sustenta-me conforme a tua palavra, para que viva.\"", "A Palavra de Deus é o oxigênio do espírito. Sem ela, a nossa fé sufoca diante das crises."],
  256: ["Efésios 4:1 - \"Andeis como é digno da vocação com que fostes chamados.\"", "Sua conduta é o cartão de visitas do Reino de Deus. Represente bem o seu Rei hoje."],
  257: ["Provérbios 11:25 - \"A alma generosa prosperará.\"", "A matemática de Deus é diferente: quanto mais você entrega e ajuda, mais você se sente pleno."],
  258: ["Salmos 42:1 - \"Como a corça anseia pelas correntes das águas, assim a minha alma anseia por ti.\"", "Reconheça sua sede espiritual. Só Deus pode saciar o vazio que o entretenimento não preenche."],
  259: ["João 8:12 - \"Quem me segue não andará em trevas.\"", "Seguir a Jesus é ter uma lanterna acesa em meio à escuridão das dúvidas deste mundo."],
  260: ["Colossenses 3:15 - \"E sede agradecidos.\"", "A gratidão não é um sentimento, é uma disciplina. Escolha três coisas para agradecer agora."],
  261: ["Salmos 119:72 - \"Melhor é para mim a lei da tua boca do que inúmeros tesouros.\"", "Valores espirituais não sofrem inflação. O que você aprende com Deus ninguém pode tirar."],
  262: ["Mateus 25:21 - \"Sobre o pouco foste fiel, sobre muito te colocarei.\"", "Não despreze os pequenos começos ou as tarefas simples. A fidelidade no pouco prepara o seu destino."],
  263: ["1 Pedro 5:10 - \"O Deus de toda a graça... ele mesmo vos há de aperfeiçoar.\"", "Você é uma obra em construção. Não desanime com suas falhas; o Arquiteto ainda está trabalhando."],
  264: ["Salmos 147:11 - \"O Senhor se agrada dos que o temem e dos que esperam na sua misericórdia.\"", "O que atrai o olhar de Deus não é o seu desempenho, mas a sua dependência d'Ele."],
  265: ["Provérbios 16:7 - \"Sendo os caminhos do homem agradáveis ao Senhor, até a seus inimigos faz que tenham paz com ele.\"", "Foque em agradar a Deus, e Ele cuidará de harmonizar os seus relacionamentos difíceis."],
  266: ["2 Coríntios 9:8 - \"Deus é poderoso para tornar abundante em vós toda graça.\"", "Deus não te dá apenas o suficiente; Ele te dá sobras para que você possa transbordar na vida de outros."],
  267: ["Salmos 119:28 - \"A minha alma consome-se de tristeza; fortalece-me segundo a tua palavra.\"", "Nos dias de desânimo profundo, deixe que as promessas bíblicas sejam o seu suporte emocional."],
  268: ["Lucas 10:42 - \"Maria escolheu a boa parte, a qual não lhe será tirada.\"", "Em um dia ocupado, escolha o que é eterno. Estar aos pés de Jesus é mais importante do que estar correndo."],
  269: ["Salmos 34:10 - \"Aos que buscam ao Senhor, bem nenhum faltará.\"", "Falta de recursos não é falta de cuidado. Deus sabe exatamente do que você precisa e quando enviar."],
  270: ["Hebreus 11:6 - \"Sem fé é impossível agradar a Deus.\"", "A fé é o idioma do céu. Fale com Deus hoje acreditando que He é real e recompensador."],
  271: ["Provérbios 14:12 - \"Há caminho que parece direito ao homem, mas o seu fim são os caminhos da morte.\"", "Não confie apenas no seu instinto. Consulte a bússola da Palavra de Deus."],
  272: ["Salmos 119:133 - \"Não se assenhore de mim iniquidade alguma.\"", "Peça a Deus para que nenhum hábito ruim ou vício domine sua vontade hoje."],
  273: ["1 João 2:1 - \"Se alguém pecar, temos um Advogado para com o Pai, Jesus Cristo.\"", "O pecado traz culpa, mas o arrependimento traz o perdão imediato de quem nos defende."],
  274: ["Salmos 126:3 - \"Grandes coisas fez o Senhor por nós, pelas quais estamos alegres.\"", "Pare um minuto para olhar para trás e celebrar as vitórias que Deus já te deu."],
  275: ["Romanos 12:11 - \"Não sejais vagarosos no cuidado; sede fervorosos no espírito, servindo ao Senhor.\"", "Coloque paixão naquilo que você faz para Deus. O entusiasmo é o brilho da alma."],
  276: ["Salmos 119:164 - \"Sete vezes no dia te louvo pelos teus justos juízos.\"", "Crie pausas de louvor durante o seu dia. Que a adoração seja o seu ritmo constante."],
  277: ["2 Coríntios 5:14 - \"Porque o amor de Cristo nos constrange.\"", "Que a motivação para todas as suas escolhas hoje seja o reconhecimento do amor que He teve por você."],
  278: ["Salmos 119:114 - \"Tu és o meu refúgio e o meu escudo; espero na tua palavra.\"", "Quando se sentir exposto aos ataques da vida, esconda-se nas promessas que Deus escreveu para você."],
  279: ["Mateus 5:14 - \"Não se pode esconder uma cidade edificada sobre um monte.\"", "Sua fé não deve ser secreta. Viva de tal modo que sua vida aponte para o alto."],
  280: ["Provérbios 15:23 - \"O homem se alegra em dar uma resposta adequada; e a palavra dita a seu tempo, quão boa é!\"", "Peça a Deus o timing certo. Falar a coisa certa na hora errada pode ferir; peça discernimento."],
  281: ["Romanos 8:18 - \"As aflições deste tempo presente não são para comparar com a glória que em nós há de ser revelada.\"", "O sofrimento atual tem data de validade; a glória que te espera é eterna."],
  282: ["Salmos 37:37 - \"Nota o homem íntegro... porque o fim desse homem é a paz.\"", "O caminho da honestidade pode ser mais longo, mas o destino final é o único que oferece repouso real."],
  283: ["Tiago 1:27 - \"A religião pura... é esta: visitar os órfãos e as viúvas nas suas tribulações.\"", "O evangelho que agrada a Deus tem mãos que ajudam e pés que visitam quem sofre."],
  284: ["Filipenses 2:5 - \"Haja em vós o mesmo sentimento que houve também em Cristo Jesus.\"", "Antes de reagir, pergunte-se: \"Como Jesus olharia para esta pessoa ou situação agora?\""],
  285: ["Salmos 119:143 - \"Tribulação e angústia se apoderaram de mim; mas os teus mandamentos são o meu prazer.\"", "Mesmo sob pressão, a Bíblia pode ser o oásis onde você recupera o fôlego."],
  286: ["Efésios 6:11 - \"Revesti-vos de toda a armadura de Deus.\"", "O mundo espiritual é real. Não saia de casa hoje sem a couraça da justiça e o escudo da fé."],
  287: ["Provérbios 22:6 - \"Instrui a criança no caminho em que deve andar...\"", "Investir na próxima geração é o maior legado que você pode deixar. Ensine pelo exemplo."],
  288: ["Salmos 55:17 - \"De tarde e de manhã e ao meio-dia orarei... e ele ouvirá a minha voz.\"", "Não reserve Deus apenas para o início do dia. Faça \"pausas de oração\" para recalibrar a alma."],
  289: ["João 16:33 - \"Tenho-vos dito isto, para que em mim tenhais paz.\"", "A paz de Jesus é fruto de Suas palavras. Ouça-O mais do que ouve os jornais e as redes sociais."],
  290: ["Colossenses 3:23 - \"E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor.\"", "A mediocridade não combina com quem serve ao Rei. Faça o seu melhor hoje, mesmo nas tarefas ocultas."],
  291: ["Salmos 119:59 - \"Considerei os meus caminhos, e voltei os meus pés para os teus testemunhos.\"", "De vez em quando, pare e recalcule a rota. Se você se desviou, hoje é dia de voltar."],
  292: ["Mateus 10:29 - \"Não se vendem dois pardais por um asse? E nenhum deles cairá em terra sem a vontade de vosso Pai.\"", "Se Deus controla o voo de um pássaro, He certamente está no controle dos detalhes do seu dia."],
  293: ["1 Pedro 1:8 - \"Ao qual, não o tendo visto, amais.\"", "O amor por Deus não depende de visões, mas de uma convicção profunda de quem He é."],
  294: ["Salmos 145:9 - \"O Senhor é bom para todos, e as suas misericórdias são sobre todas as suas obras.\"", "Se Deus é bom até para quem não O conhece, imagine o que He tem guardado para você, que é filho."],
  295: ["Provérbios 18:10 - \"Torre forte é o nome do Senhor; a ela correrá o justo, e estará em alto refúgio.\"", "Quando se sentir vulnerável, pronuncie o nome de Jesus. He é o abrigo que o inimigo não alcança."],
  296: ["2 Coríntios 4:17 - \"Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória.\"", "O que parece pesado hoje será visto como \"leve\" quando olharmos da perspectiva da eternidade."],
  297: ["Salmos 119:101 - \"Desviei os meus pés de todo caminho mau, para guardar a tua palavra.\"", "Santidade é feita de pequenas decisões diárias de dizer \"não\" ao que nos afasta de Deus."],
  298: ["Hebreus 12:14 - \"Segui a paz com todos, e a santificação, sem a qual ninguém verá o Senhor.\"", "A paz externa e a pureza interna são as duas trilhas que nos levam à presença de Deus."],
  299: ["Salmos 130:5 - \"Aguardo ao Senhor; a minha alma o aguarda, e espero na sua palavra.\"", "A espera cristã é cheia de expectativa, não de tédio. Algo bom está vindo da parte d'Ele."],
  300: ["1 Tessalonicenses 5:21 - \"Examinai tudo. Retende o que é bom.\"", "Seja seletivo com o que você consome. Guarde no coração apenas o que edifica e te faz crescer."],
  301: ["Salmos 119:97 - \"Oh! quanto amo a tua lei! É a minha meditação em todo o dia.\"", "Falar de Deus é bom, mas pensar na Palavra de Deus o tempo todo transforma o caráter."],
  302: ["Marcos 12:30 - \"Amarás, pois, ao Senhor teu Deus de todo o teu coração.\"", "O amor a Deus deve ser integral: emocional, espiritual, intelectual e físico."],
  303: ["Salmos 34:15 - \"Os olhos do Senhor estão sobre os justos, e os seus ouvidos atentos ao seu clamor.\"", "Você tem a atenção total do Criador. He não está distraído quando você ora."],
  304: ["Gálatas 6:7 - \"Tudo o que o homem semear, isso também ceifará.\"", "O futuro é um campo que você planta hoje. Escolha sementes de bondade e fidelidade."],
  305: ["Salmos 119:11 - \"Escondi a tua palavra no meu coração, para eu não pecar contra ti.\"", "O melhor cofre para a Bíblia não é a estante, mas a sua memória e o seu afeto."],
  306: ["Tiago 4:10 - \"Humilhai-vos perante o Senhor, e ele vos exaltará.\"", "O caminho para cima, no Reino de Deus, começa de joelhos."],
  307: ["Salmos 23:6 - \"Certamente que a bondade e a misericórdia me seguirão todos os dias da minha vida.\"", "Você não está sendo perseguido pelo azar ou pelo destino, mas pela bondade de Deus."],
  308: ["Salmos 119:112 - \"Inclinei o meu coração a guardar os teus estatutos para sempre.\"", "A fidelidade não é um evento, é uma direção que você escolhe manter todos os dias."],
  309: ["Mateus 6:31 - \"Não andeis, pois, inquietos, dizendo: Que comeremos, ou que beberemos?\"", "O mesmo Deus que criou a vida é quem garante o sustento dela. Confie na provisão."],
  310: ["Provérbios 13:3 - \"O que guarda a sua boca conserva a sua alma.\"", "Nem todo pensamento precisa virar palavra. O silêncio estratégico protege sua paz espiritual."],
  311: ["Romanos 15:4 - \"Para que pela paciência... tenhamos esperança.\"", "A Bíblia foi escrita para nos consolar e nos dar fôlego quando a jornada parece longa demais."],
  312: ["Salmos 119:140 - \"A tua palavra é muito pura; por isso o teu servo a ama.\"", "Em um mundo de valores mistos, a Bíblia é o único padrão de pureza que não falha."],
  313: ["Efésios 5:1 - \"Sede, pois, imitadores de Deus, como filhos amados.\"", "Um filho imita o pai naturalmente. Que seus gestos hoje revelem a paternidade divina."],
  314: ["Provérbios 10:9 - \"Quem anda em integridade anda seguro.\"", "A verdade te livra do medo de ser descoberto. Nada é mais leve do que uma consciência limpa."],
  315: ["Salmos 119:169 - \"Chegue a ti o meu clamor, ó Senhor; dá-me entendimento.\"", "Ore por clareza mental. Muitas vezes o problema não é a falta de solução, mas a falta de visão."],
  316: ["2 Coríntios 5:21 - \"Aquele que não conheceu pecado, o fez pecado por nós.\"", "Nunca esqueça a troca: Jesus levou sua culpa para que você pudesse levar a justiça d'Ele."],
  317: ["Hebreus 10:35 - \"Não rejeiteis, pois, a vossa confiança, que tem grande galardão.\"", "Não jogue a toalha agora. A sua confiança em Deus será recompensada no tempo certo."],
  318: ["Salmos 37:39 - \"A salvação dos justos vem do Senhor; ele é a sua fortaleza no tempo da angústia.\"", "Quando o cerco apertar, lembre-se: Deus é um castelo onde o mal não consegue entrar."],
  319: ["Tiago 1:5 - \"E, se algum de vós tem falta de sabedoria, peça-a a Deus.\"", "Deus não te julga por não saber; He te honra quando você reconhece que precisa d'Ele."],
  320: ["Filipenses 1:21 - \"Porque para mim o viver é Cristo, e o morrer é ganho.\"", "Quando Cristo é o centro da vida, perdemos o medo do futuro e até da morte."],
  321: ["Salmos 119:57 - \"O Senhor é a minha porção; eu disse que guardaria as tuas palavras.\"", "Se você tiver Deus, você tem a melhor parte da herança. O resto é apenas complemento."],
  322: ["Lucas 12:34 - \"Porque, onde estiver o vosso tesouro, ali estará também o vosso coração.\"", "Avalie onde você investe seu tempo e dinheiro; é ali que o seu coração está morando."],
  323: ["1 João 1:9 - \"Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar.\"", "O perdão de Deus não é relutante; é uma promessa baseada na fidelidade d'Ele, não no seu mérito."],
  324: ["Salmos 119:162 - \"Folgo com a tua palavra, como aquele que acha um grande despojo.\"", "Encontre alegria na leitura bíblica como se estivesse descobrindo uma fortuna hoje."],
  325: ["Colossenses 3:1 - \"Buscai as coisas que são de cima, onde Cristo está assentado.\"", "Mantenha sua mente sintonizada na eternidade enquanto seus pés caminham na terra."],
  326: ["Provérbios 19:17 - \"Ao Senhor empresta o que se compadece do pobre.\"", "O que você faz pelos necessitados, Deus registra como uma dívida que He mesmo pagará."],
  327: ["Salmos 143:10 - \"Ensina-me a fazer a tua vontade, pois és o meu Deus.\"", "Ser submisso à vontade de Deus é a maior prova de inteligência espiritual."],
  328: ["João 15:11 - \"Tenho-vos dito isto, para que a minha alegria permaneça em vós.\"", "A alegria cristã não é uma euforia passageira, é uma satisfação permanente em Jesus."],
  329: ["1 Pedro 2:2 - \"Desejai afetuosamente... o leite espiritual puro.\"", "Assim como o corpo sente fome, a alma precisa de alimento bíblico diário para crescer."],
  330: ["Salmos 119:41 - \"Venham sobre mi também as tuas misericórdias, ó Senhor.\"", "Peça que a bondade de Deus te alcance hoje, onde quer que você esteja."],
  331: ["Mateus 24:13 - \"Mas aquele que perseverar até ao fim será salvo.\"", "A vida com Deus é uma maratona, não uma corrida de cem metros. Mantenha o passo."],
  332: ["2 Pedro 3:18 - \"Antes crescei na graça e conhecimento de nosso Senhor.\"", "Não se contente com o nível espiritual de ontem. Busque ser mais maduro hoje."],
  333: ["Salmos 139:10 - \"Até ali a tua mão me guiará e a tua destra me susterá.\"", "Não importa quão longe ou difícil seja o lugar, a mão de Deus chega lá antes de você."],
  334: ["Provérbios 16:24 - \"As palavras suaves são favos de mel, doces para a alma.\"", "Use sua fala para adoçar a vida de alguém hoje. Seja um incentivador."],
  335: ["1 Coríntios 2:9 - \"As coisas que o olho não viu... são as que Deus preparou.\"", "O que Deus planejou para o seu futuro supera qualquer expectativa que você possa ter."],
  336: ["Salmos 119:135 - \"Faze resplandecer o teu rosto sobre o teu servo.\"", "A aprovação de Deus é o maior prêmio que podemos receber. Busque o sorriso do Pai."],
  337: ["Apocalipse 3:20 - \"Eis que estou à porta, e bato.\"", "Jesus não invade; He convida. Abra a porta do seu coração para He participar do seu dia."],
  338: ["Salmos 119:174 - \"Anseio pela tua salvação, Senhor; a tua lei é o meu prazer.\"", "Que o seu prazer não esteja nas coisas que passam, mas na vontade dAquele que é eterno."],
  339: ["Hebreus 12:1 - \"Corramos com perseverança a carreira que nos está proposta.\"", "O caminho foi traçado por Deus. Seu trabalho é não parar e manter o fôlego na fé."],
  340: ["Provérbios 3:26 - \"Porque o Senhor será a tua esperança e guardará os teus pés.\"", "A segurança real não vem de muros ou contas bancárias, mas da proteção divina."],
  341: ["Mateus 25:23 - \"Bem está, servo bom e fiel. Sobre o pouco foste fiel...\"", "O reconhecimento de Deus é para quem persiste na obediência, mesmo no que parece pequeno."],
  342: ["Salmos 119:160 - \"A soma da tua palavra é a verdade.\"", "Não isole versículos; viva o conjunto da obra de Deus. A verdade completa traz liberdade."],
  343: ["1 João 5:11 - \"E o testemunho é este: que Deus nos deu a vida eterna.\"", "O maior presente que você recebeu não é para esta vida, é para a eternidade com Ele."],
  344: ["Salmos 27:4 - \"Uma coisa pedi ao Senhor... que possa morar na sua casa.\"", "Simplifique seus pedidos. No fim das contas, a presença de Deus é a única coisa necessária."],
  345: ["Romanos 8:31 - \"Se Deus é por nós, quem será contra nós?\"", "A soberania de Deus anula qualquer força que tente te impedir de cumprir o seu propósito."],
  346: ["2 Timóteo 1:12 - \"Eu sei em quem tenho crido e estou certo de que ele é poderoso.\"", "A convicção não vem de sentir, mas de conhecer o caráter dAquele a quem entregamos a vida."],
  347: ["Salmos 119:165 - \"Grande paz têm os que amam a tua lei.\"", "A paz é o resultado natural de uma vida que se alinha com os princípios bíblicos."],
  348: ["Filipenses 4:13 - \"Tudo posso naquele que me fortalece.\"", "Lembre-se: \"tudo\" inclui suportar escassez, fartura, vitórias e perdas com a mesma fé."],
  349: ["Tiago 4:14 - \"Que é a vossa vida? É um vapor que aparece por um pouco...\"", "A brevidade da vida deve nos ensinar a valorizar o que é eterno e quem nós amamos."],
  350: ["Salmos 119:111 - \"Os teus testemunhos... são o regozijo do meu coração.\"", "Faça das promessas de Deus a sua maior fonte de alegria hoje."],
  351: ["Mateus 28:20 - \"E eis que eu estou convosco todos os dias.\"", "Cristo não é um Deus de feriados ou domingos; He está no seu café da manhã e no seu trabalho."],
  352: ["Provérbios 4:23 - \"Sobre tudo o que se deve guardar, guarda o teu coração.\"", "Não deixe que a amargura do mundo contamine a fonte da sua vida interna."],
  353: ["1 Coríntios 13:13 - \"Agora, pois, permanecem a fé, a esperança e o amor; mas o maior destes é o amor.\"", "Se você tiver tudo mas não tiver amor, não terá nada. Priorize o amor hoje."],
  354: ["Salmos 119:176 - \"Andei errante como ovelha desgarrada; busca o teu servo.\"", "Se você se perdeu, Deus está te procurando. Basta um sussurro para He te encontrar."],
  355: ["Judas 1:24 - \"Àquele que é poderoso para vos guardar de tropeçar.\"", "Sua estabilidade não depende da sua força, mas da mão d'Ele que te segura firme."],
  356: ["Salmos 31:19 - \"Oh! quão grande é a tua bondade, que guardaste para os que te temem.\"", "Há tesouros de bondade que Deus reservou especificamente para quem escolhe honrá-Lo."],
  357: ["Colossenses 4:2 - \"Perseverai em oração, velando nela com ação de graças.\"", "Não ore apenas pedindo; ore vigiando e agradecendo pelo que já foi feito."],
  358: ["Salmos 119:89 - \"Para sempre, ó Senhor, a tua palavra permanece no céu.\"", "Governos caem, modas passam, mas o que Deus disse continua valendo hoje."],
  359: ["João 14:2 - \"Na casa de meu Pai há muitas moradas... vou preparar-vos lugar.\"", "O seu destino final é uma casa preparada com carinho pelo próprio Jesus."],
  360: ["Salmos 119:105 - \"Lâmpada para os meus pés é a tua palavra e luz para o meu caminho.\"", "Que as Escrituras continuem sendo o seu guia no próximo ano e em todos os outros."],
  361: ["Hebreus 13:8 - \"Jesus Cristo é o mesmo ontem, e hoje, e eternamente.\"", "Em um mundo de mudanças drásticas, você está ancorado em Quem nunca muda."],
  362: ["Salmos 103:1 - \"Bendize, ó minha alma, ao Senhor, e tudo o que há em mi bendiga o seu santo nome.\"", "Que o seu louvor seja completo: mente, corpo e espírito unidos para agradecer."],
  363: ["2 Coríntios 13:14 - \"A graça do Senhor Jesus... seja com todos vós.\"", "Que o favor imerecido de Deus seja a atmosfera onde você respira e vive."],
  364: ["Salmos 150:6 - \"Tudo quanto tem fôlego louve ao Senhor.\"", "Se você está respirando agora, você tem um motivo para celebrar o Criador."],
  365: ["Apocalipse 22:21 - \"A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém!\"", "Encerre este ciclo sabendo que a Graça foi quem te trouxe até aqui e é ela quem te levará além."]
};

/**
 * Mapeia os dados brutos para o formato Devotional, tratando a separação de referência e versículo.
 */
const staticReflections: Record<number, Devotional> = {};

Object.entries(rawData).forEach(([dayStr, [key, refl]]) => {
  const day = parseInt(dayStr);
  const parts = key.split(' - ');
  const reference = parts[0];
  const verse = parts.slice(1).join(' - ').replace(/^"|"$/g, '');
  staticReflections[day] = { verse, reference, reflection: refl };
});

export const getLocalReflection = (day: number, plan: DayPlan): Devotional => {
  if (staticReflections[day]) {
    return staticReflections[day];
  }

  // Fix: Safe extraction of book name from union types (string | ReadingSegment)
  const getBookNameSafely = (s: any) => {
    if (!s) return "Bíblia";
    if (typeof s === 'string') return s.split(' ')[0];
    return s.book;
  };

  // Fallback baseado no plano
  const bookName = (plan.segments && plan.segments.length > 0) 
    ? getBookNameSafely(plan.segments[0]) 
    : getBookNameSafely(plan.ot);

  return {
    verse: "Lâmpada para os meus pés é tua palavra, e luz para o meu caminho.",
    reference: "Salmo 119:105",
    reflection: `Hoje sua jornada de fé passa por ${bookName}. Deixe que a palavra de Deus renove suas esperanças e guie seus passos com sabedoria.`
  };
};
